import { useEffect, useState } from "react";
import ImagePreviewModal from "../../components/common/ImagePreviewModal";
import { approveFoundReport, getPendingFoundReports, rejectFoundReport } from "../../services/foundReportService";
import { showError, showSuccess } from "../../utils/toast";
import "../../styles/FoundReports.css";

function FoundReports() {
  const [reports, setReports] = useState([]); const [selected, setSelected] = useState(null); const [preview, setPreview] = useState(null); const [remarks, setRemarks] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { getPendingFoundReports().then(setReports).catch((error) => showError(error.response?.data?.message || "Could not load Found Reports.")); }, []);
  const review = async (approved) => { if (!selected) return; try { setSaving(true); const updated = approved ? await approveFoundReport(selected._id, remarks) : await rejectFoundReport(selected._id, remarks); setReports((current) => current.filter((report) => report._id !== updated._id)); showSuccess(approved ? "Found Report approved; the case is now Found." : "Found Report rejected."); setSelected(null); setRemarks(""); } catch (error) { showError(error.response?.data?.message || "Could not review Found Report."); } finally { setSaving(false); } };
  return <section className="found-reports-page"><header><h2 className="page-title">Found Reports</h2><p>Review officer submissions before a case is marked as found.</p></header>{reports.length === 0 ? <div className="found-reports-empty">No Found Reports are awaiting review.</div> : <div className="found-reports-grid">{reports.map((report) => <article key={report._id} className="found-report-card"><span className="found-report-pending">Pending Approval</span><h3>{report.person?.name}</h3><p>{report.person?.caseNumber}</p><dl><div><dt>Officer</dt><dd>{report.reportedBy?.name}</dd></div><div><dt>Found date</dt><dd>{new Date(report.foundDate).toLocaleDateString("en-IN")}</dd></div><div><dt>Location</dt><dd>{report.location}</dd></div><div><dt>Submitted</dt><dd>{new Date(report.createdAt).toLocaleString("en-IN")}</dd></div></dl><button onClick={() => setSelected(report)} type="button">View & Review</button></article>)}</div>}{selected && <div className="found-report-backdrop" onMouseDown={() => setSelected(null)}><div className="found-report-modal" onMouseDown={(event) => event.stopPropagation()}><button className="found-report-close" type="button" onClick={() => setSelected(null)}>×</button><h2>Found Report Details</h2><p><strong>{selected.person?.name}</strong> · {selected.person?.caseNumber}</p><p>Reported by {selected.reportedBy?.name} ({selected.reportedBy?.station || selected.reportedBy?.email})</p><label>Found location<input readOnly value={selected.location} /></label><label>Description<textarea readOnly value={selected.description} /></label>{selected.recognitionId && <p>Recognition: {selected.recognitionId.videoName} · {selected.recognitionId.cameraLocation}{selected.recognitionId.matches?.[0] ? ` · AI confidence ${(selected.recognitionId.matches[0].confidence * 100).toFixed(1)}%` : ""}</p>}{selected.evidenceImages?.length > 0 && <div className="found-report-evidence">{selected.evidenceImages.map((image, index) => <img key={image} onClick={() => setPreview({ images: selected.evidenceImages, index })} src={`http://localhost:5000/uploads/${image}`} alt="Evidence" />)}</div>}<label>Review remarks<textarea value={remarks} onChange={(event) => setRemarks(event.target.value)} placeholder="Optional remarks for the officer" /></label><div className="found-report-review-actions"><button disabled={saving} type="button" onClick={() => review(false)}>Reject</button><button disabled={saving} type="button" onClick={() => review(true)}>{saving ? "Saving..." : "Approve"}</button></div></div></div>}{preview && <ImagePreviewModal images={preview.images} index={preview.index} onIndexChange={(index) => setPreview((current) => ({ ...current, index }))} onClose={() => setPreview(null)} alt="Found report evidence" />}</section>;
}
export default FoundReports;
